os: osx
osx_image: xcode10.3
language: swift
env: 
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/CoreTCX.xcworkspace
  - IOS_FRAMEWORK_SCHEME="CoreTCX"
  - EXAMPLE_SCHEME="CoreTCX-Example"
  matrix:
  - DESTINATION="OS=12.4,name=iPhone 6 Plus" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="iphonesimulator12.4"
  
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  
  - xcodebuild -workspace "$WORKSPACE" -list
  
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
