name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build iOS
      run: xcodebuild -workspace "Example/CoreTCX.xcworkspace" -scheme "CoreTCX" -destination "OS=14.3,name=iPhone 12 Pro" -configuration Release ONLY_ACTIVE_ARCH=NO clean build | xcpretty
    #- name: Run tests
      #run: swift test -v
